version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: kintai-bot-postgres
    environment:
      POSTGRES_USER: kintaiuser
      POSTGRES_PASSWORD: kintaipassword
      POSTGRES_DB: kintaidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: